credentials:
- password: pass1
  research_count: 39
  username: user1
- password: pass2
  research_count: 3
  username: user2
- email: user3@gmail.com
  password: ''
  research_count: 0
  username: user3
- email: user4@gmail.com
  password: pass4
  research_count: 7
  username: user4
- email: user5@gmail.com
  password: pass5
  research_count: 0
  username: user5
- email: user6
  password: pass6
  research_count: 0
  username: user6
- email: user9
  password: pass9
  research_count: 2
  username: user9
- email: e3@gmail.com
  password: pass10
  research_count: 0
  username: user10
- email: a
  password: a
  research_count: 0
  username: a
- email: b
  password: b
  research_count: 0
  username: b
- email: gm@gmail.com
  password: tusc
  research_count: 15
  username: Tusann
- email: roy@gmail.com
  password: expenses
  research_count: 0
  username: roy
- email: a@gma.com
  password: tool
  research_count: 2
  username: tool
